### ISSUE TITLE
Here the code runs wrong, is the code missing, can you help

### ISSUE THREAD

**Issue by zjutzs** [johnMinelli/MovingObjectRemoval#1]
if(matchesMIN_MATCH_COUNT:
        F, mask = cv2.findFundamentalMat(matches1,matches2,cv2.FM_LMEDS)
          # we select only inlier points
        matches1 = matches1[mask.ravel()==1]
        matches2 = matches2[mask.ravel()==1]
Here the code runs wrong, is the code missing, can you help

**Comment by johnMinelli** [comment]
Hello, I don't know why, but the ipynb viewer does not show the code correctly. If you download it or check the raw version, you'll see the missing piece:
https://github.com/johnMinelli/MovingObjectRemoval/blob/8645f5187d95d4639b8ac2f9308e49727289d533/video_objects_removal.ipynb#L329C1-L347C51

**Comment by zjutzs** [comment]
Thank you very much !
